# Configuration for automatically labeling pull requests based on changed files
# Format for actions/labeler@v5

# Java code changes
java:
  - changed-files:
    - any-glob-to-any-file: '**/*.java'

# Test changes
tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/test/**/*'
      - '**/*Test.java'
      - '**/*Tests.java'

# Configuration changes
configuration:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.properties'
      - '**/pom.xml'

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**/*'

# Frontend/Templates
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/resources/templates/**/*'
      - 'src/main/resources/static/**/*'
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'

# Controllers
controller:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/controller/**/*'

# Services
service:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/service/**/*'

# Repository/Data Layer
repository:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/repository/**/*'

# Models/Entities
model:
  - changed-files:
    - any-glob-to-any-file: 'src/main/java/**/model/**/*'

# Security
security:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/main/java/**/config/SecurityConfig.java'
      - 'src/main/java/**/service/*UserDetails*.java'

# CI/CD
ci-cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'
